apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
        - image: aniach/my-service
          imagePullPolicy: IfNotPresent
          name: my-service
      restartPolicy: Always
